--- #YAML:1.0
name:                Win32-Watir
version:             0.03
abstract:            Perl extension for automating Internet Explorer.
license:             ~
author:              
    - Kazuhito Shimizu <kazuhito.shimizu@gmail.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Win32::OLE:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
