--- #YAML:1.0
name:               Win32-Watir
version:            0.05
abstract:           Perl extension for automating Internet Explorer.
author:
    - Kazuhito Shimizu <kazuhito.shimizu@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Win32:       0
    Win32::OLE:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
